# Generated by Django 5.2.15 on 2026-08-12 16:18

import plane.db.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.JSONField(default=plane.db.models.user.get_default_theme),
        ),
    ]
